//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistManager.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomMaterial
    {
        public int CustomMaterialID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<System.DateTime> ReciveDate { get; set; }
        public int PatientID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public int DoctorID { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public Nullable<int> ClinicID { get; set; }
        public Nullable<bool> Payed { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
