//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistManager.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageCategory
    {
        public ImageCategory()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int ImageCategoryID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ICollection<Image> Images { get; set; }
    }
}
