//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistManager.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpperationMaterial
    {
        public int OpperationID { get; set; }
        public int ItemID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual opperation opperation { get; set; }
    }
}
