//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistManager.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientPayment
    {
        public PatientPayment()
        {
            this.PaymentReceipts = new HashSet<PaymentReceipt>();
        }
    
        public int PatientPaymentID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public string UserID { get; set; }
        public int ClinicID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Clinic Clinic { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual ICollection<PaymentReceipt> PaymentReceipts { get; set; }
    }
}
