//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistManager.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionValue
    {
        public int ValueID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string SessionValue1 { get; set; }
        public string PrortyName { get; set; }
    
        public virtual SessionsStat SessionsStat { get; set; }
    }
}
