//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistManager.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionsStat
    {
        public SessionsStat()
        {
            this.SessionValues = new HashSet<SessionValue>();
        }
    
        public int SessionID { get; set; }
        public string UserID { get; set; }
        public string SessionName { get; set; }
    
        public virtual ICollection<SessionValue> SessionValues { get; set; }
    }
}
