//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistManager.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public Storage()
        {
            this.RecivingItems = new HashSet<RecivingItem>();
            this.Warehouses = new HashSet<Warehouse>();
        }
    
        public int StorageID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public int ClinicID { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual ICollection<RecivingItem> RecivingItems { get; set; }
        public virtual ICollection<Warehouse> Warehouses { get; set; }
    }
}
