//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistManager.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public Treatment()
        {
            this.MaterialTreatments = new HashSet<MaterialTreatment>();
        }
    
        public int TeratmentID { get; set; }
        public string Description { get; set; }
        public int AppointmentID { get; set; }
        public int DoctorID { get; set; }
        public int PatientID { get; set; }
        public int OpperationID { get; set; }
        public string ToothSideNumber { get; set; }
        public string ToothNumber { get; set; }
        public Nullable<decimal> OpperationCost { get; set; }
        public decimal TeratmentCost { get; set; }
        public int ClinicID { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Clinic Clinic { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual ICollection<MaterialTreatment> MaterialTreatments { get; set; }
        public virtual opperation opperation { get; set; }
    }
}
