//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistManager.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int WarehouseID { get; set; }
        public int StorageID { get; set; }
        public int ItemID { get; set; }
        public int Available { get; set; }
        public int Reserved { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
